#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $KC_DB_USERNAME WITH PASSWORD '$KC_DB_PASSWORD';
    CREATE DATABASE keycloak OWNER $KC_DB_USERNAME;

    CREATE USER $HOME_DB_USERNAME WITH PASSWORD '$HOME_DB_PASSWORD';
    CREATE DATABASE home_service OWNER $HOME_DB_USERNAME;

    CREATE USER $DEVICE_DB_USERNAME WITH PASSWORD '$DEVICE_DB_PASSWORD';
    CREATE DATABASE device_service OWNER $DEVICE_DB_USERNAME;

    CREATE USER $ROOM_DB_USERNAME WITH PASSWORD '$ROOM_DB_PASSWORD';
    CREATE DATABASE room_service OWNER $ROOM_DB_USERNAME;

    CREATE USER $USER_PROFILE_DB_USERNAME WITH PASSWORD '$USER_PROFILE_DB_PASSWORD';
    CREATE DATABASE user_profile_service OWNER $USER_PROFILE_DB_USERNAME;

    CREATE USER $ACCESS_CONTROL_DB_USERNAME WITH PASSWORD '$ACCESS_CONTROL_DB_PASSWORD';
    CREATE DATABASE access_control_service OWNER $ACCESS_CONTROL_DB_USERNAME;
EOSQL
