parent=keycloak.v2
import=common/keycloak
styles=css/theme.css
stylesCommon=
scripts=js/domovoy-password-toggle.js js/domovoy-theme-toggle.js
locales=ru,en

kcFormClass=kc-form
kcFormGroupClass=kc-field
kcFormGroupLabelClass=kc-label-wrap
kcFormLabelClass=kc-label
kcFormLabelTextClass=
kcLabelWrapperClass=kc-label-wrap
kcLabelClass=kc-label
kcInputWrapperClass=kc-input-wrap
kcInputClass=kc-input
kcInputGroup=kc-input-group
kcInputHelperTextBeforeClass=kc-field-help
kcInputHelperTextAfterClass=kc-field-help
kcInputErrorMessageClass=kc-field-error
kcInputRequiredClass=required
kcCheckboxClass=kc-checkbox
kcCheckboxInputClass=
kcCheckboxLabelClass=
